[package]
name = "merkle"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.8"
stellar-strkey = "0.0.13"
stellar-xdr = "22.1.0"
